import { KanbanCard, KanbanColumn, CardTag } from '../types/kanban';

export const INITIAL_TAGS: CardTag[] = [
  { id: 'tag-1', name: 'Frontend', color: 'bg-blue-500/20 text-blue-300 border-blue-500/40' },
  { id: 'tag-2', name: 'UI/UX Design', color: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40' },
  { id: 'tag-3', name: 'Backend API', color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40' },
  { id: 'tag-4', name: 'Client Feedback', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-5', name: 'SEO & Perf', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' },
  { id: 'tag-6', name: 'Urgent Bug', color: 'bg-rose-500/20 text-rose-300 border-rose-500/40' },
];

export const DEFAULT_TAG_OPTIONS: CardTag[] = [
  ...INITIAL_TAGS,
  { id: 'tag-lead-new', name: 'New Lead', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' },
  { id: 'tag-lead-dm', name: 'DM Sent', color: 'bg-sky-500/20 text-sky-300 border-sky-500/40' },
  { id: 'tag-lead-call', name: 'Call Booked', color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40' },
  { id: 'tag-lead-followup', name: 'Follow Up', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-lead-closed', name: 'Closed Won', color: 'bg-teal-500/20 text-teal-300 border-teal-500/40' },
  // Call Statuses (DNP - Did Not Pick)
  { id: 'tag-dnp-1', name: 'DNP 1', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-dnp-2', name: 'DNP 2', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-dnp-3', name: 'DNP 3', color: 'bg-orange-500/20 text-orange-300 border-orange-500/40' },
  { id: 'tag-dnp-4', name: 'DNP 4', color: 'bg-orange-500/20 text-orange-300 border-orange-500/40' },
  { id: 'tag-dnp-5', name: 'DNP 5', color: 'bg-rose-500/20 text-rose-300 border-rose-500/40' },
  { id: 'tag-dnp-6', name: 'DNP 6 (Exhausted)', color: 'bg-red-500/25 text-red-300 border-red-500/50' },
];

export const AGENCY_MEMBERS = [
  { id: 'user-1', name: 'Leo Vance', role: 'Lead Architect', avatarColor: '#3b82f6' },
  { id: 'user-2', name: 'Elena Rostova', role: 'UI/UX Director', avatarColor: '#06b6d4' },
  { id: 'user-3', name: 'Marcus Chen', role: 'Fullstack Engineer', avatarColor: '#6366f1' },
  { id: 'user-4', name: 'Aria Bennett', role: 'Product Strategist', avatarColor: '#ec4899' },
  { id: 'user-5', name: 'Devon Miles', role: 'QA & DevOps', avatarColor: '#10b981' },
];

export const INITIAL_COLUMNS: KanbanColumn[] = [
  { id: 'col-backlog', title: 'Backlog / Ideas', order: 0, colorDot: '#64748b' },
  { id: 'col-progress', title: 'In Progress', order: 1, colorDot: '#3b82f6' },
  { id: 'col-review', title: 'Code & QA Review', order: 2, colorDot: '#f59e0b' },
  { id: 'col-client', title: 'Client Approval', order: 3, colorDot: '#a855f7' },
  { id: 'col-done', title: 'Done / Shipped', order: 4, colorDot: '#10b981' },
];

export const INITIAL_CARDS: KanbanCard[] = [
  {
    id: 'card-1',
    columnId: 'col-backlog',
    title: 'Brand Identity & Design System V2',
    description: 'Create typography guidelines, Bluish dark glass component tokens, and icon asset catalog for Webglow agency projects.',
    priority: 'medium',
    tags: [INITIAL_TAGS[1]],
    assignees: [AGENCY_MEMBERS[1]],
    dueDate: '2026-09-25',
    checklist: [
      { id: 'chk-1', text: 'Color palette definition & contrast checks', completed: true },
      { id: 'chk-2', text: 'Button & interactive component states', completed: true },
      { id: 'chk-3', text: 'Export Figma token variables to Tailwind config', completed: false },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'card-2',
    columnId: 'col-progress',
    title: 'Multiplayer Realtime WebSockets Engine',
    description: 'Implement dual-engine syncing: Supabase Realtime broadcast channels with fallback to BroadcastChannel for seamless local multi-tab preview.',
    priority: 'urgent',
    tags: [INITIAL_TAGS[0], INITIAL_TAGS[2]],
    assignees: [AGENCY_MEMBERS[0], AGENCY_MEMBERS[2]],
    dueDate: '2026-09-18',
    checklist: [
      { id: 'chk-4', text: 'Setup Supabase client & postgres schema', completed: true },
      { id: 'chk-5', text: 'Presence tracking for active collaborators', completed: true },
      { id: 'chk-6', text: 'Live card drag-and-drop broadcast channel', completed: false },
      { id: 'chk-7', text: 'Optimistic UI update handler with reconciliation', completed: false },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'card-3',
    columnId: 'col-progress',
    title: 'Agency Client Portal Hero Redesign',
    description: 'Modernize hero banner with sleek bluish glowing gradients, glassmorphism cards, and interactive 3D stats counter.',
    priority: 'high',
    tags: [INITIAL_TAGS[1], INITIAL_TAGS[0]],
    assignees: [AGENCY_MEMBERS[1]],
    dueDate: '2026-09-20',
    checklist: [
      { id: 'chk-8', text: 'Create responsive mockup in Figma', completed: true },
      { id: 'chk-9', text: 'Implement Tailwind hero section', completed: true },
      { id: 'chk-10', text: 'Animate metrics counter with smooth ease-out', completed: false },
    ],
    order: 1,
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'card-4',
    columnId: 'col-review',
    title: 'Stripe Billing & Subscription Webhooks',
    description: 'Handle customer.subscription.updated and checkout.session.completed with idempotent database transactions.',
    priority: 'high',
    tags: [INITIAL_TAGS[2]],
    assignees: [AGENCY_MEMBERS[2]],
    dueDate: '2026-09-19',
    checklist: [
      { id: 'chk-11', text: 'Stripe CLI webhook forwarding tests', completed: true },
      { id: 'chk-12', text: 'Handle customer grace period downgrade', completed: true },
      { id: 'chk-13', text: 'Automated invoice receipt email delivery', completed: true },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'card-5',
    columnId: 'col-client',
    title: 'E-commerce Checkout Optimization Report',
    description: 'Present A/B test results to client stakeholders showing a 22.4% uplift in conversions after 1-step checkout rollout.',
    priority: 'medium',
    tags: [INITIAL_TAGS[3], INITIAL_TAGS[4]],
    assignees: [AGENCY_MEMBERS[3]],
    dueDate: '2026-09-22',
    checklist: [
      { id: 'chk-14', text: 'Export analytics funnel charts', completed: true },
      { id: 'chk-15', text: 'Compile executive deck summary', completed: true },
      { id: 'chk-16', text: 'Schedule review call with client team', completed: false },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'card-6',
    columnId: 'col-done',
    title: 'Core Web Vitals & Lighthouse 100 Score Audit',
    description: 'Optimized next/image priority loading, preconnected Google Fonts, reduced unused CSS, achieved 99+ mobile Lighthouse score.',
    priority: 'low',
    tags: [INITIAL_TAGS[4]],
    assignees: [AGENCY_MEMBERS[4]],
    dueDate: '2026-09-15',
    checklist: [
      { id: 'chk-17', text: 'Compress WebP and AVIF assets', completed: true },
      { id: 'chk-18', text: 'Defer non-critical analytics scripts', completed: true },
      { id: 'chk-19', text: 'Verify LCP < 1.2s across 3G throttle', completed: true },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
];
