import { KanbanCard, KanbanColumn, CardTag } from '../types/kanban';

export const INITIAL_TAGS: CardTag[] = [
  { id: 'tag-1', name: 'Frontend', color: 'bg-blue-500/20 text-blue-300 border-blue-500/40' },
  { id: 'tag-2', name: 'UI/UX Design', color: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40' },
  { id: 'tag-3', name: 'Backend API', color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40' },
  { id: 'tag-4', name: 'Client Feedback', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-5', name: 'SEO & Perf', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' },
  { id: 'tag-6', name: 'Urgent Bug', color: 'bg-rose-500/20 text-rose-300 border-rose-500/40' },
];

export const DEFAULT_TAG_OPTIONS: CardTag[] = [
  ...INITIAL_TAGS,
  { id: 'tag-lead-new', name: 'New Lead', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' },
  { id: 'tag-lead-dm', name: 'DM Sent', color: 'bg-sky-500/20 text-sky-300 border-sky-500/40' },
  { id: 'tag-lead-call', name: 'Call Booked', color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40' },
  { id: 'tag-lead-followup', name: 'Follow Up', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-lead-closed', name: 'Closed Won', color: 'bg-teal-500/20 text-teal-300 border-teal-500/40' },
  // Call Statuses (DNP - Did Not Pick)
  { id: 'tag-dnp-1', name: 'DNP 1', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-dnp-2', name: 'DNP 2', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' },
  { id: 'tag-dnp-3', name: 'DNP 3', color: 'bg-orange-500/20 text-orange-300 border-orange-500/40' },
  { id: 'tag-dnp-4', name: 'DNP 4', color: 'bg-orange-500/20 text-orange-300 border-orange-500/40' },
  { id: 'tag-dnp-5', name: 'DNP 5', color: 'bg-rose-500/20 text-rose-300 border-rose-500/40' },
  { id: 'tag-dnp-6', name: 'DNP 6 (Exhausted)', color: 'bg-red-500/25 text-red-300 border-red-500/50' },
];

export const AGENCY_MEMBERS = [
  { id: 'user-1', name: 'Leo Vance', role: 'Lead Architect', avatarColor: '#3b82f6' },
  { id: 'user-2', name: 'Elena Rostova', role: 'UI/UX Director', avatarColor: '#06b6d4' },
  { id: 'user-3', name: 'Marcus Chen', role: 'Fullstack Engineer', avatarColor: '#6366f1' },
  { id: 'user-4', name: 'Aria Bennett', role: 'Product Strategist', avatarColor: '#ec4899' },
  { id: 'user-5', name: 'Devon Miles', role: 'QA & DevOps', avatarColor: '#10b981' },
];

export const INITIAL_COLUMNS: KanbanColumn[] = [
  { id: 'col-backlog', title: 'Backlog / Ideas', order: 0, colorDot: '#64748b' },
  { id: 'col-progress', title: 'In Progress', order: 1, colorDot: '#3b82f6' },
  { id: 'col-review', title: 'Code & QA Review', order: 2, colorDot: '#f59e0b' },
  { id: 'col-client', title: 'Client Approval', order: 3, colorDot: '#a855f7' },
  { id: 'col-done', title: 'Done / Shipped', order: 4, colorDot: '#10b981' },
];

export const INITIAL_CARDS: KanbanCard[] = [
  {
    id: 'card-1',
    columnId: 'col-backlog',
    title: 'Brand Identity & Design System V2',
    description: 'Create typography guidelines, Bluish dark glass component tokens, and icon asset catalog for Webglow agency projects.',
    priority: 'medium',
    tags: [INITIAL_TAGS[1]],
    assignees: [AGENCY_MEMBERS[1]],
    dueDate: '2026-09-25',
    checklist: [
      { id: 'chk-1', text: 'Color palette definition & contrast checks', completed: true },
      { id: 'chk-2', text: 'Button & interactive component states', completed: true },
      { id: 'chk-3', text: 'Export Figma token variables to Tailwind config', completed: false },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'card-2',
    columnId: 'col-progress',
    title: 'Multiplayer Realtime WebSockets Engine',
    description: 'Implement dual-engine syncing: Supabase Realtime broadcast channels with fallback to BroadcastChannel for seamless local multi-tab preview.',
    priority: 'urgent',
    tags: [INITIAL_TAGS[0], INITIAL_TAGS[2]],
    assignees: [AGENCY_MEMBERS[0], AGENCY_MEMBERS[2]],
    dueDate: '2026-09-18',
    checklist: [
      { id: 'chk-4', text: 'Setup Supabase client & postgres schema', completed: true },
      { id: 'chk-5', text: 'Presence tracking for active collaborators', completed: true },
      { id: 'chk-6', text: 'Live card drag-and-drop broadcast channel', completed: false },
      { id: 'chk-7', text: 'Optimistic UI update handler with reconciliation', completed: false },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'card-3',
    columnId: 'col-progress',
    title: 'Agency Client Portal Hero Redesign',
    description: 'Modernize hero banner with sleek bluish glowing gradients, glassmorphism cards, and interactive 3D stats counter.',
    priority: 'high',
    tags: [INITIAL_TAGS[1], INITIAL_TAGS[0]],
    assignees: [AGENCY_MEMBERS[1]],
    dueDate: '2026-09-20',
    checklist: [
      { id: 'chk-8', text: 'Create responsive mockup in Figma', completed: true },
      { id: 'chk-9', text: 'Implement Tailwind hero section', completed: true },
      { id: 'chk-10', text: 'Animate metrics counter with smooth ease-out', completed: false },
    ],
    order: 1,
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'card-4',
    columnId: 'col-review',
    title: 'Stripe Billing & Subscription Webhooks',
    description: 'Handle customer.subscription.updated and checkout.session.completed with idempotent database transactions.',
    priority: 'high',
    tags: [INITIAL_TAGS[2]],
    assignees: [AGENCY_MEMBERS[2]],
    dueDate: '2026-09-19',
    checklist: [
      { id: 'chk-11', text: 'Stripe CLI webhook forwarding tests', completed: true },
      { id: 'chk-12', text: 'Handle customer grace period downgrade', completed: true },
      { id: 'chk-13', text: 'Automated invoice receipt email delivery', completed: true },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'card-5',
    columnId: 'col-client',
    title: 'E-commerce Checkout Optimization Report',
    description: 'Present A/B test results to client stakeholders showing a 22.4% uplift in conversions after 1-step checkout rollout.',
    priority: 'medium',
    tags: [INITIAL_TAGS[3], INITIAL_TAGS[4]],
    assignees: [AGENCY_MEMBERS[3]],
    dueDate: '2026-09-22',
    checklist: [
      { id: 'chk-14', text: 'Export analytics funnel charts', completed: true },
      { id: 'chk-15', text: 'Compile executive deck summary', completed: true },
      { id: 'chk-16', text: 'Schedule review call with client team', completed: false },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'card-6',
    columnId: 'col-done',
    title: 'Core Web Vitals & Lighthouse 100 Score Audit',
    description: 'Optimized next/image priority loading, preconnected Google Fonts, reduced unused CSS, achieved 99+ mobile Lighthouse score.',
    priority: 'low',
    tags: [INITIAL_TAGS[4]],
    assignees: [AGENCY_MEMBERS[4]],
    dueDate: '2026-09-15',
    checklist: [
      { id: 'chk-17', text: 'Compress WebP and AVIF assets', completed: true },
      { id: 'chk-18', text: 'Defer non-critical analytics scripts', completed: true },
      { id: 'chk-19', text: 'Verify LCP < 1.2s across 3G throttle', completed: true },
    ],
    order: 0,
    createdAt: new Date(Date.now() - 3600000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
];

export const INITIAL_CLIENTS: import('../types/kanban').ClientRecord[] = [
  {
    id: 'client-1',
    name: 'Apex Dynamics',
    type: 'both',
    status: 'active',
    services: 'Next.js Web Platform, Enterprise Portal & Monthly SLA Retainer',
    revenueCollected: 38500,
    monthlyRetainer: 2200,
    contactName: 'David Sterling',
    contactEmail: 'david@apexdynamics.io',
    contactPhone: '+1 (555) 234-8901',
    startDate: '2025-11-10',
    notes: 'Primary retainer client. Quarterly performance review scheduled.',
    createdAt: new Date(Date.now() - 86400000 * 90).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-2',
    name: 'Luminova Health',
    type: 'production',
    status: 'completed',
    services: 'HIPAA-Compliant Patient Portal & Brand Identity System',
    revenueCollected: 42000,
    contactName: 'Dr. Claire Zhang',
    contactEmail: 'claire@luminova.health',
    contactPhone: '+1 (555) 891-2345',
    startDate: '2026-01-15',
    completionDate: '2026-06-30',
    notes: 'Production successfully delivered with 100% Lighthouse mobile audit.',
    createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-3',
    name: 'FinScale Cloud Technologies',
    type: 'maintenance',
    status: 'active',
    services: '24/7 Security Patches, Uptime Monitoring & DevOps SLA',
    revenueCollected: 19200,
    monthlyRetainer: 2400,
    contactName: 'Jordan Miller',
    contactEmail: 'jmiller@finscale.tech',
    contactPhone: '+1 (555) 432-1098',
    startDate: '2025-10-01',
    notes: 'Monthly retainer billed on the 1st of every month.',
    createdAt: new Date(Date.now() - 86400000 * 150).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-4',
    name: 'NovaCraft Studios',
    type: 'both',
    status: 'active',
    services: '3D WebGL Portfolio Design & Bi-weekly Maintenance Updates',
    revenueCollected: 26800,
    monthlyRetainer: 1800,
    contactName: 'Sophia Reyes',
    contactEmail: 'sophia@novacraft.design',
    contactPhone: '+1 (555) 765-4321',
    startDate: '2026-02-01',
    notes: 'Award-winning creative portfolio with ongoing asset updates.',
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-5',
    name: 'Riverstone Luxury Real Estate',
    type: 'production',
    status: 'completed',
    services: 'High-conversion MLS Real Estate Search Engine & Lead Generation Funnel',
    revenueCollected: 31500,
    contactName: 'Michael Thorne',
    contactEmail: 'm.thorne@riverstone.luxury',
    contactPhone: '+1 (555) 345-6789',
    startDate: '2026-03-01',
    completionDate: '2026-07-15',
    notes: 'Full payment collected upon production launch approval.',
    createdAt: new Date(Date.now() - 86400000 * 80).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-6',
    name: 'Vanguard AI Labs',
    type: 'maintenance',
    status: 'active',
    services: 'Model Evaluation Dashboard Maintenance & Cloud Infrastructure Retainer',
    revenueCollected: 14000,
    monthlyRetainer: 2000,
    contactName: 'Ethan Vance',
    contactEmail: 'ethan@vanguard-ai.co',
    contactPhone: '+1 (555) 654-9870',
    startDate: '2026-04-01',
    notes: 'Under ongoing monthly maintenance agreement.',
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const getInitialAttendanceForDate = (dateStr: string): import('../types/kanban').AttendanceRecord[] => [
  {
    id: `att-${dateStr}-1`,
    memberId: 'user-1',
    memberName: 'Leo Vance',
    memberRole: 'Lead Architect',
    avatarColor: '#3b82f6',
    date: dateStr,
    status: 'present',
    checkInTime: '09:05 AM',
    workMode: 'office',
    notes: 'Sprint planning & lead architecture review',
  },
  {
    id: `att-${dateStr}-2`,
    memberId: 'user-2',
    memberName: 'Elena Rostova',
    memberRole: 'UI/UX Director',
    avatarColor: '#06b6d4',
    date: dateStr,
    status: 'remote',
    checkInTime: '09:18 AM',
    workMode: 'remote',
    notes: 'Figma component guidelines & design audit',
  },
  {
    id: `att-${dateStr}-3`,
    memberId: 'user-3',
    memberName: 'Marcus Chen',
    memberRole: 'Fullstack Engineer',
    avatarColor: '#6366f1',
    date: dateStr,
    status: 'present',
    checkInTime: '09:30 AM',
    workMode: 'office',
    notes: 'Supabase realtime sync & backend optimizations',
  },
  {
    id: `att-${dateStr}-4`,
    memberId: 'user-4',
    memberName: 'Aria Bennett',
    memberRole: 'Product Strategist',
    avatarColor: '#ec4899',
    date: dateStr,
    status: 'remote',
    checkInTime: '09:45 AM',
    workMode: 'remote',
    notes: 'Client maintenance discovery calls',
  },
  {
    id: `att-${dateStr}-5`,
    memberId: 'user-5',
    memberName: 'Devon Miles',
    memberRole: 'QA & DevOps',
    avatarColor: '#10b981',
    date: dateStr,
    status: 'late',
    checkInTime: '10:15 AM',
    workMode: 'office',
    notes: 'Automated CI/CD checks & production health audit',
  },
];
